**Lab:** Lab 6  
# Deep Learning for NLP

**Name:** Mohammad Buhamad

**Student ID:** [2240005142]

In [7]:
import pandas as pd

df = pd.read_csv(
    "07-yelp-dataset.txt",
    sep="\t",
    names=["review", "label"]
)

print("Number of reviews:", len(df))

df.head()

Number of reviews: 1000

                                              review  label
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [8]:
print(df["label"].value_counts())

label
1    500
0    500
Name: count, dtype: int64

In [9]:
import re

def preprocess_text(text):

    # 1. Convert to lowercase
    text = text.lower()

    # 2. Remove punctuation and special characters
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # 3. Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

df["review"] = df["review"].apply(preprocess_text)

df.head()

                                              review  label
0                               wow loved this place      1
1                                  crust is not good      0
2           not tasty and the texture was just nasty      0
3  stopped by during the late may bank holiday of...      1
4  the selection on the menu was great and so wer...      1

In [10]:
from sklearn.model_selection import train_test_split

X = df["review"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training reviews:", len(X_train))
print("Testing reviews:", len(X_test))

Training reviews: 800
Testing reviews: 200

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=1000, lowercase=True)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

Training TF-IDF shape: (800, 1000)
Testing TF-IDF shape: (200, 1000)

In [12]:
!pip install torch
import torch
import torch.nn as nn

X_train_tensor = torch.FloatTensor(
    X_train_tfidf.toarray()
)

X_test_tensor = torch.FloatTensor(
    X_test_tfidf.toarray()
)

y_train_tensor = torch.FloatTensor(
    y_train.values
).reshape(-1, 1)

Collecting torch
  Downloading torch-2.14.0-cp312-cp312-win_amd64.whl.metadata (38 kB)
Requirement already satisfied: filelock in d:\donlwd\new folder\lib\site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in d:\donlwd\new folder\lib\site-packages (from torch) (4.15.0)
Collecting setuptools>=77.0.3 (from torch)
  Downloading setuptools-84.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in d:\donlwd\new folder\lib\site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in d:\donlwd\new folder\lib\site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in d:\donlwd\new folder\lib\site-packages (from torch) (2024.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\donlwd\new folder\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\donlwd\new folder\lib\site-packages (from jinja2->torch) (2.1.3)
Downloading torch-2.14.0-cp312-cp312-win_amd64.whl (124.1 MB)
   ---------------------------------------- 0.0/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.1/124.1 MB 1.6 MB/s eta 0:01:18
   ---------------------------------------- 0.1/124.1 MB 1.6 MB/s eta 0:01:18
   ---------------------------------------- 0.1/124.1 MB 558.5 kB/s eta 0:03:43
   ---------------------------------------- 0.1/124.1 MB 708.1 kB/s eta 0:02:56
   ---------------------------------------- 0.2/124.1 MB 903.5 kB/s eta 0:02:18
   ---------------------------------------- 0.2/124.1 MB 769.9 kB/s eta 0:02:41
   ---------------------------------------- 0.3/124.1 MB 916.0 kB/s eta 0:02:16
   ---------------------------------------- 0.4/124.1 MB 1.1 MB/s eta 0:01:55
   ---------------------------------------- 0.5/124.1 MB 1.2 MB/s eta 0:01:45
   ---------------------------------------- 0.6/124.1 MB 1.2 MB/s eta 0:01:42
   ---------------------------------------- 0.8/124.1 MB 1.6 MB/s eta 0:01:20
   ---------------------------------------- 0.9/124.1 MB 1.7 MB/s eta 0:01:13
   ---------------------------------------- 1.0/124.1 MB 1.8 MB/s eta 0:01:09
   ---------------------------------------- 1.3/124.1 MB 2.0 MB/s eta 0:01:01
   ---------------------------------------- 1.4/124.1 MB 2.1 MB/s eta 0:00:59
   ---------------------------------------- 1.4/124.1 MB 2.1 MB/s eta 0:00:59
    --------------------------------------- 1.7/124.1 MB 2.2 MB/s eta 0:00:56
    --------------------------------------- 2.2/124.1 MB 2.7 MB/s eta 0:00:46
    --------------------------------------- 2.7/124.1 MB 3.1 MB/s eta 0:00:40
    --------------------------------------- 3.1/124.1 MB 3.4 MB/s eta 0:00:37
    --------------------------------------- 3.1/124.1 MB 3.2 MB/s eta 0:00:38
   - -------------------------------------- 3.3/124.1 MB 3.4 MB/s eta 0:00:36
   - -------------------------------------- 3.3/124.1 MB 3.4 MB/s eta 0:00:36
   - -------------------------------------- 3.8/124.1 MB 3.5 MB/s eta 0:00:35
   - -------------------------------------- 4.4/124.1 MB 3.8 MB/s eta 0:00:32
   - -------------------------------------- 4.9/124.1 MB 4.1 MB/s eta 0:00:29
   - -------------------------------------- 5.4/124.1 MB 4.3 MB/s eta 0:00:28
   - -------------------------------------- 5.9/124.1 MB 4.7 MB/s eta 0:00:26
   -- ------------------------------------- 6.5/124.1 MB 4.9 MB/s eta 0:00:24
   -- ------------------------------------- 7.1/124.1 MB 5.1 MB/s eta 0:00:23
   -- ------------------------------------- 7.5/124.1 MB 5.4 MB/s eta 0:00:22
   -- ------------------------------------- 8.2/124.1 MB 5.6 MB/s eta 0:00:21
   -- ------------------------------------- 8.3/124.1 MB 5.6 MB/s eta 0:00:21
   -- ------------------------------------- 8.4/124.1 MB 5.5 MB/s eta 0:00:22
   -- ------------------------------------- 8.6/124.1 MB 5.3 MB/s eta 0:00:22
   -- ------------------------------------- 9.0/124.1 MB 5.5 MB/s eta 0:00:22
   --- ------------------------------------ 9.6/124.1 MB 5.6 MB/s eta 0:00:21
   --- ------------------------------------ 10.1/124.1 MB 5.8 MB/s eta 0:00:20
   --- ------------------------------------ 10.6/124.1 MB 7.3 MB/s eta 0:00:16
   --- ------------------------------------ 11.1/124.1 MB 7.9 MB/s eta 0:00:15
   --- ------------------------------------ 11.6/124.1 MB 8.4 MB/s eta 0:00:14
   --- ------------------------------------ 12.1/124.1 MB 9.2 MB/s eta 0:00:13
   --- ------------------------------------ 12.1/124.1 MB 9.2 MB/s eta 0:00:13
   --- ------------------------------------ 12.1/124.1 MB 9.2 MB/s eta 0:00:13
   --- ------------------------------------ 12.3/124.1 MB 8.3 MB/s eta 0:00:14
   ---- ----------------------------------- 13.0/124.1 MB 8.3 MB/s eta 0:00:14
   ---- ----------------------------------- 13.5/124.1 MB 8.7 MB/s eta 0:00:13
   ---- ----------------------------------- 14.0/124.1 MB 9.1 MB/s eta 0:00:13
   ---- ----------------------------------- 14.4/124.1 MB 9.2 MB/s eta 0:00:12
   ---- ----------------------------------- 14.6/124.1 MB 9.1 MB/s eta 0:00:13
   ---- ----------------------------------- 15.0/124.1 MB 9.0 MB/s eta 0:00:13
   ----- ---------------------------------- 15.5/124.1 MB 8.8 MB/s eta 0:00:13
   ----- ---------------------------------- 16.1/124.1 MB 8.8 MB/s eta 0:00:13
   ----- ---------------------------------- 16.4/124.1 MB 9.0 MB/s eta 0:00:13
   ----- ---------------------------------- 16.8/124.1 MB 8.6 MB/s eta 0:00:13
   ----- ---------------------------------- 17.2/124.1 MB 8.5 MB/s eta 0:00:13
   ----- ---------------------------------- 17.8/124.1 MB 8.6 MB/s eta 0:00:13
   ----- ---------------------------------- 18.4/124.1 MB 8.6 MB/s eta 0:00:13
   ------ --------------------------------- 18.9/124.1 MB 9.6 MB/s eta 0:00:11
   ------ --------------------------------- 19.4/124.1 MB 9.4 MB/s eta 0:00:12
   ------ --------------------------------- 19.9/124.1 MB 9.6 MB/s eta 0:00:11
   ------ --------------------------------- 20.4/124.1 MB 9.5 MB/s eta 0:00:11
   ------ --------------------------------- 20.9/124.1 MB 9.5 MB/s eta 0:00:11
   ------ --------------------------------- 21.5/124.1 MB 9.5 MB/s eta 0:00:11
   ------- -------------------------------- 22.1/124.1 MB 9.5 MB/s eta 0:00:11
   ------- -------------------------------- 22.6/124.1 MB 10.7 MB/s eta 0:00:10
   ------- -------------------------------- 23.2/124.1 MB 10.7 MB/s eta 0:00:10
   ------- -------------------------------- 23.8/124.1 MB 10.6 MB/s eta 0:00:10
   ------- -------------------------------- 24.3/124.1 MB 10.6 MB/s eta 0:00:10
   -------- ------------------------------- 24.9/124.1 MB 11.1 MB/s eta 0:00:09
   -------- ------------------------------- 25.4/124.1 MB 11.1 MB/s eta 0:00:09
   -------- ------------------------------- 25.9/124.1 MB 11.1 MB/s eta 0:00:09
   -------- ------------------------------- 26.4/124.1 MB 10.9 MB/s eta 0:00:09
   -------- ------------------------------- 27.0/124.1 MB 11.5 MB/s eta 0:00:09
   -------- ------------------------------- 27.5/124.1 MB 11.5 MB/s eta 0:00:09
   --------- ------------------------------ 28.1/124.1 MB 11.5 MB/s eta 0:00:09
   --------- ------------------------------ 28.6/124.1 MB 11.5 MB/s eta 0:00:09
   --------- ------------------------------ 29.0/124.1 MB 11.1 MB/s eta 0:00:09
   --------- ------------------------------ 29.6/124.1 MB 11.1 MB/s eta 0:00:09
   --------- ------------------------------ 30.2/124.1 MB 11.3 MB/s eta 0:00:09
   --------- ------------------------------ 30.8/124.1 MB 11.3 MB/s eta 0:00:09
   ---------- ----------------------------- 31.4/124.1 MB 11.1 MB/s eta 0:00:09
   ---------- ----------------------------- 32.0/124.1 MB 11.5 MB/s eta 0:00:09
   ---------- ----------------------------- 32.6/124.1 MB 11.3 MB/s eta 0:00:09
   ---------- ----------------------------- 33.0/124.1 MB 11.1 MB/s eta 0:00:09
   ---------- ----------------------------- 33.4/124.1 MB 11.3 MB/s eta 0:00:09
   ---------- ----------------------------- 34.0/124.1 MB 11.1 MB/s eta 0:00:09
   ----------- ---------------------------- 34.5/124.1 MB 11.1 MB/s eta 0:00:09
   ----------- ---------------------------- 34.9/124.1 MB 11.1 MB/s eta 0:00:09
   ----------- ---------------------------- 35.5/124.1 MB 11.1 MB/s eta 0:00:08
   ----------- ---------------------------- 35.5/124.1 MB 11.1 MB/s eta 0:00:08
   ----------- ---------------------------- 36.2/124.1 MB 11.1 MB/s eta 0:00:08
   ----------- ---------------------------- 36.2/124.1 MB 10.4 MB/s eta 0:00:09
   ----------- ---------------------------- 36.7/124.1 MB 10.4 MB/s eta 0:00:09
   ----------- ---------------------------- 37.1/124.1 MB 10.4 MB/s eta 0:00:09
   ------------ --------------------------- 37.6/124.1 MB 10.2 MB/s eta 0:00:09
   ------------ --------------------------- 38.1/124.1 MB 10.4 MB/s eta 0:00:09
   ------------ --------------------------- 38.6/124.1 MB 10.4 MB/s eta 0:00:09
   ------------ --------------------------- 39.1/124.1 MB 10.6 MB/s eta 0:00:09
   ------------ --------------------------- 39.6/124.1 MB 10.4 MB/s eta 0:00:09
   ------------ --------------------------- 40.2/124.1 MB 10.6 MB/s eta 0:00:08
   ------------- -------------------------- 40.7/124.1 MB 10.6 MB/s eta 0:00:08
   ------------- -------------------------- 41.2/124.1 MB 10.4 MB/s eta 0:00:08
   ------------- -------------------------- 41.7/124.1 MB 10.6 MB/s eta 0:00:08
   ------------- -------------------------- 42.1/124.1 MB 10.4 MB/s eta 0:00:08
   ------------- -------------------------- 42.6/124.1 MB 10.2 MB/s eta 0:00:08
   ------------- -------------------------- 43.1/124.1 MB 10.1 MB/s eta 0:00:09
   -------------- ------------------------- 43.8/124.1 MB 10.4 MB/s eta 0:00:08
   -------------- ------------------------- 44.2/124.1 MB 10.2 MB/s eta 0:00:08
   -------------- ------------------------- 44.8/124.1 MB 10.4 MB/s eta 0:00:08
   -------------- ------------------------- 44.9/124.1 MB 10.2 MB/s eta 0:00:08
   -------------- ------------------------- 45.3/124.1 MB 9.8 MB/s eta 0:00:09
   -------------- ------------------------- 45.8/124.1 MB 10.1 MB/s eta 0:00:08
   -------------- ------------------------- 46.3/124.1 MB 9.8 MB/s eta 0:00:08
   --------------- ------------------------ 46.9/124.1 MB 10.4 MB/s eta 0:00:08
   --------------- ------------------------ 47.3/124.1 MB 10.6 MB/s eta 0:00:08
   --------------- ------------------------ 47.9/124.1 MB 10.6 MB/s eta 0:00:08
   --------------- ------------------------ 48.5/124.1 MB 10.4 MB/s eta 0:00:08
   --------------- ------------------------ 49.0/124.1 MB 10.4 MB/s eta 0:00:08
   --------------- ------------------------ 49.3/124.1 MB 10.4 MB/s eta 0:00:08
   ---------------- ----------------------- 49.8/124.1 MB 10.4 MB/s eta 0:00:08
   ---------------- ----------------------- 50.3/124.1 MB 10.1 MB/s eta 0:00:08
   ---------------- ----------------------- 50.9/124.1 MB 10.2 MB/s eta 0:00:08
   ---------------- ----------------------- 51.5/124.1 MB 10.2 MB/s eta 0:00:08
   ---------------- ----------------------- 52.0/124.1 MB 10.2 MB/s eta 0:00:08
   ---------------- ----------------------- 52.4/124.1 MB 10.6 MB/s eta 0:00:07
   ----------------- ---------------------- 52.9/124.1 MB 10.6 MB/s eta 0:00:07
   ----------------- ---------------------- 53.5/124.1 MB 10.4 MB/s eta 0:00:07
   ----------------- ---------------------- 54.0/124.1 MB 10.4 MB/s eta 0:00:07
   ----------------- ---------------------- 54.6/124.1 MB 10.4 MB/s eta 0:00:07
   ----------------- ---------------------- 55.2/124.1 MB 11.1 MB/s eta 0:00:07
   ----------------- ---------------------- 55.5/124.1 MB 10.7 MB/s eta 0:00:07
   ------------------ --------------------- 56.1/124.1 MB 10.9 MB/s eta 0:00:07
   ------------------ --------------------- 56.6/124.1 MB 10.9 MB/s eta 0:00:07
   ------------------ --------------------- 57.2/124.1 MB 10.7 MB/s eta 0:00:07
   ------------------ --------------------- 57.6/124.1 MB 10.7 MB/s eta 0:00:07
   ------------------ --------------------- 57.9/124.1 MB 10.6 MB/s eta 0:00:07
   ------------------ --------------------- 58.4/124.1 MB 10.6 MB/s eta 0:00:07
   ------------------- -------------------- 59.1/124.1 MB 10.6 MB/s eta 0:00:07
   ------------------- -------------------- 59.6/124.1 MB 10.9 MB/s eta 0:00:06
   ------------------- -------------------- 60.3/124.1 MB 10.9 MB/s eta 0:00:06
   ------------------- -------------------- 60.8/124.1 MB 11.1 MB/s eta 0:00:06
   ------------------- -------------------- 61.5/124.1 MB 10.9 MB/s eta 0:00:06
   ------------------- -------------------- 62.0/124.1 MB 11.1 MB/s eta 0:00:06
   -------------------- ------------------- 62.5/124.1 MB 10.9 MB/s eta 0:00:06
   -------------------- ------------------- 63.0/124.1 MB 11.1 MB/s eta 0:00:06
   -------------------- ------------------- 63.4/124.1 MB 10.9 MB/s eta 0:00:06
   -------------------- ------------------- 63.8/124.1 MB 10.7 MB/s eta 0:00:06
   -------------------- ------------------- 64.4/124.1 MB 11.1 MB/s eta 0:00:06
   -------------------- ------------------- 65.1/124.1 MB 11.1 MB/s eta 0:00:06
   --------------------- ------------------ 65.6/124.1 MB 11.1 MB/s eta 0:00:06
   --------------------- ------------------ 66.2/124.1 MB 11.5 MB/s eta 0:00:06
   --------------------- ------------------ 66.8/124.1 MB 11.3 MB/s eta 0:00:06
   --------------------- ------------------ 67.3/124.1 MB 11.5 MB/s eta 0:00:05
   --------------------- ------------------ 67.8/124.1 MB 11.5 MB/s eta 0:00:05
   ---------------------- ----------------- 68.4/124.1 MB 11.7 MB/s eta 0:00:05
   ---------------------- ----------------- 69.0/124.1 MB 11.5 MB/s eta 0:00:05
   ---------------------- ----------------- 69.6/124.1 MB 11.9 MB/s eta 0:00:05
   ---------------------- ----------------- 69.9/124.1 MB 11.5 MB/s eta 0:00:05
   ---------------------- ----------------- 70.3/124.1 MB 11.3 MB/s eta 0:00:05
   ---------------------- ----------------- 71.0/124.1 MB 11.3 MB/s eta 0:00:05
   ----------------------- ---------------- 71.5/124.1 MB 11.3 MB/s eta 0:00:05
   ----------------------- ---------------- 72.1/124.1 MB 11.3 MB/s eta 0:00:05
   ----------------------- ---------------- 72.7/124.1 MB 11.3 MB/s eta 0:00:05
   ----------------------- ---------------- 73.3/124.1 MB 11.3 MB/s eta 0:00:05
   ----------------------- ---------------- 73.8/124.1 MB 11.3 MB/s eta 0:00:05
   ----------------------- ---------------- 74.4/124.1 MB 11.5 MB/s eta 0:00:05
   ------------------------ --------------- 75.0/124.1 MB 11.5 MB/s eta 0:00:05
   ------------------------ --------------- 75.4/124.1 MB 11.3 MB/s eta 0:00:05
   ------------------------ --------------- 75.8/124.1 MB 11.3 MB/s eta 0:00:05
   ------------------------ --------------- 76.3/124.1 MB 11.1 MB/s eta 0:00:05
   ------------------------ --------------- 77.0/124.1 MB 11.1 MB/s eta 0:00:05
   ------------------------ --------------- 77.4/124.1 MB 10.9 MB/s eta 0:00:05
   ------------------------- -------------- 78.1/124.1 MB 11.3 MB/s eta 0:00:05
   ------------------------- -------------- 78.6/124.1 MB 11.1 MB/s eta 0:00:05
   ------------------------- -------------- 79.1/124.1 MB 11.1 MB/s eta 0:00:05
   ------------------------- -------------- 79.5/124.1 MB 10.9 MB/s eta 0:00:05
   ------------------------- -------------- 80.1/124.1 MB 11.1 MB/s eta 0:00:04
   -------------------------- ------------- 80.7/124.1 MB 11.3 MB/s eta 0:00:04
   -------------------------- ------------- 81.3/124.1 MB 11.3 MB/s eta 0:00:04
   -------------------------- ------------- 81.9/124.1 MB 11.3 MB/s eta 0:00:04
   -------------------------- ------------- 82.4/124.1 MB 11.3 MB/s eta 0:00:04
   -------------------------- ------------- 83.0/124.1 MB 11.5 MB/s eta 0:00:04
   -------------------------- ------------- 83.6/124.1 MB 11.3 MB/s eta 0:00:04
   --------------------------- ------------ 84.0/124.1 MB 11.3 MB/s eta 0:00:04
   --------------------------- ------------ 84.4/124.1 MB 10.9 MB/s eta 0:00:04
   --------------------------- ------------ 85.0/124.1 MB 10.9 MB/s eta 0:00:04
   --------------------------- ------------ 85.4/124.1 MB 10.9 MB/s eta 0:00:04
   --------------------------- ------------ 85.9/124.1 MB 10.7 MB/s eta 0:00:04
   --------------------------- ------------ 86.4/124.1 MB 11.1 MB/s eta 0:00:04
   ---------------------------- ----------- 86.9/124.1 MB 10.9 MB/s eta 0:00:04
   ---------------------------- ----------- 87.4/124.1 MB 11.1 MB/s eta 0:00:04
   ---------------------------- ----------- 87.9/124.1 MB 11.1 MB/s eta 0:00:04
   ---------------------------- ----------- 88.3/124.1 MB 10.9 MB/s eta 0:00:04
   ---------------------------- ----------- 88.9/124.1 MB 11.1 MB/s eta 0:00:04
   ---------------------------- ----------- 89.3/124.1 MB 10.9 MB/s eta 0:00:04
   ---------------------------- ----------- 89.9/124.1 MB 10.9 MB/s eta 0:00:04
   ----------------------------- ---------- 90.5/124.1 MB 10.9 MB/s eta 0:00:04
   ----------------------------- ---------- 91.1/124.1 MB 10.9 MB/s eta 0:00:04
   ----------------------------- ---------- 91.8/124.1 MB 11.1 MB/s eta 0:00:03
   ----------------------------- ---------- 92.3/124.1 MB 10.9 MB/s eta 0:00:03
   ----------------------------- ---------- 92.9/124.1 MB 10.9 MB/s eta 0:00:03
   ------------------------------ --------- 93.3/124.1 MB 10.9 MB/s eta 0:00:03
   ------------------------------ --------- 93.8/124.1 MB 10.9 MB/s eta 0:00:03
   ------------------------------ --------- 94.3/124.1 MB 11.3 MB/s eta 0:00:03
   ------------------------------ --------- 94.8/124.1 MB 11.3 MB/s eta 0:00:03
   ------------------------------ --------- 95.4/124.1 MB 11.3 MB/s eta 0:00:03
   ------------------------------ --------- 96.0/124.1 MB 11.5 MB/s eta 0:00:03
   ------------------------------- -------- 96.6/124.1 MB 11.5 MB/s eta 0:00:03
   ------------------------------- -------- 97.2/124.1 MB 11.5 MB/s eta 0:00:03
   ------------------------------- -------- 97.8/124.1 MB 11.5 MB/s eta 0:00:03
   ------------------------------- -------- 98.2/124.1 MB 11.7 MB/s eta 0:00:03
   ------------------------------- -------- 98.5/124.1 MB 11.5 MB/s eta 0:00:03
   ------------------------------- -------- 99.0/124.1 MB 11.3 MB/s eta 0:00:03
   -------------------------------- ------- 99.4/124.1 MB 11.3 MB/s eta 0:00:03
   -------------------------------- ------- 99.9/124.1 MB 11.5 MB/s eta 0:00:03
   ------------------------------- ------- 100.5/124.1 MB 11.5 MB/s eta 0:00:03
   ------------------------------- ------- 101.0/124.1 MB 11.3 MB/s eta 0:00:03
   ------------------------------- ------- 101.5/124.1 MB 11.1 MB/s eta 0:00:03
   -------------------------------- ------ 102.0/124.1 MB 11.1 MB/s eta 0:00:02
   -------------------------------- ------ 102.3/124.1 MB 10.9 MB/s eta 0:00:02
   -------------------------------- ------ 102.9/124.1 MB 10.9 MB/s eta 0:00:02
   -------------------------------- ------ 103.4/124.1 MB 11.1 MB/s eta 0:00:02
   -------------------------------- ------ 104.0/124.1 MB 10.9 MB/s eta 0:00:02
   -------------------------------- ------ 104.5/124.1 MB 10.9 MB/s eta 0:00:02
   --------------------------------- ----- 105.1/124.1 MB 10.9 MB/s eta 0:00:02
   --------------------------------- ----- 105.6/124.1 MB 10.7 MB/s eta 0:00:02
   --------------------------------- ----- 106.1/124.1 MB 10.9 MB/s eta 0:00:02
   --------------------------------- ----- 106.6/124.1 MB 10.7 MB/s eta 0:00:02
   --------------------------------- ----- 107.2/124.1 MB 10.9 MB/s eta 0:00:02
   --------------------------------- ----- 107.7/124.1 MB 10.7 MB/s eta 0:00:02
   --------------------------------- ----- 108.2/124.1 MB 10.7 MB/s eta 0:00:02
   ---------------------------------- ---- 108.7/124.1 MB 10.9 MB/s eta 0:00:02
   ---------------------------------- ---- 109.2/124.1 MB 10.9 MB/s eta 0:00:02
   ---------------------------------- ---- 109.7/124.1 MB 10.9 MB/s eta 0:00:02

In [13]:
input_size = X_train_tensor.shape[1]

model = nn.Sequential(
    nn.Linear(input_size, 64),
    nn.ReLU(),

    nn.Linear(64, 32),
    nn.ReLU(),

    nn.Linear(32, 1)
)

print(model)

Sequential(
  (0): Linear(in_features=1000, out_features=64, bias=True)
  (1): ReLU()
  (2): Linear(in_features=64, out_features=32, bias=True)
  (3): ReLU()
  (4): Linear(in_features=32, out_features=1, bias=True)
)

In [14]:
loss_function = nn.BCEWithLogitsLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.01
)

In [15]:
epochs = 10

for epoch in range(epochs):

    model.train()

    # 1. Forward pass
    outputs = model(X_train_tensor)

    # 2. Calculate loss
    loss = loss_function(outputs, y_train_tensor)

    # 3. Backpropagation
    loss.backward()

    # 4. Update model weights
    optimizer.step()

    if (epoch + 1) % 5 == 0:
        print(
            f"Epoch {epoch + 1}/{epochs} - Loss: {loss.item():.4f}"
        )

Epoch 5/10 - Loss: 0.6582
Epoch 10/10 - Loss: 0.4963

In [16]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model.eval()

with torch.no_grad():

    test = model(X_test_tensor)

    test_probabilities = torch.sigmoid(test)

    predictions = (
        test_probabilities >= 0.5
    ).int().numpy().flatten()

accuracy = accuracy_score(
    y_test,
    predictions
)

print(f"Test Accuracy: {accuracy:.3f}")

Test Accuracy: 0.725

In [17]:
print("Classification Report:")

print(
    classification_report(
        y_test,
        predictions,
        target_names=["Negative", "Positive"]
    )
)

print("Confusion Matrix:")

print(
    confusion_matrix(
        y_test,
        predictions
    )
)

Classification Report:
              precision    recall  f1-score   support

    Negative       0.65      0.95      0.77        96
    Positive       0.92      0.52      0.66       104

    accuracy                           0.72       200
   macro avg       0.78      0.73      0.72       200
weighted avg       0.79      0.72      0.71       200

Confusion Matrix:
[[91  5]
 [50 54]]

In [18]:
!pip install gensim
import gensim
from nltk.tokenize import word_tokenize

Requirement already satisfied: gensim in d:\donlwd\new folder\lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in d:\donlwd\new folder\lib\site-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy>=1.7.0 in d:\donlwd\new folder\lib\site-packages (from gensim) (1.13.1)
Requirement already satisfied: smart_open>=1.8.1 in d:\donlwd\new folder\lib\site-packages (from gensim) (5.2.1)

In [19]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\xmoha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\xmoha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [20]:
train_tokens = [
    word_tokenize(review)
    for review in X_train
]

test_tokens = [
    word_tokenize(review)
    for review in X_test
]

In [21]:
import numpy as np

def review_to_vector(tokens, model):

    vectors = []

    for word in tokens:

        if word in model.wv:
            vectors.append(model.wv[word])

    if len(vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

In [23]:
import gensim

w2v_model = gensim.models.Word2Vec(
    train_tokens,
    vector_size=200,
    window=5,
    min_count=1,
    sg=1
)

In [24]:
X_train_w2v = np.array([
    review_to_vector(tokens, w2v_model)
    for tokens in train_tokens
])

X_test_w2v = np.array([
    review_to_vector(tokens, w2v_model)
    for tokens in test_tokens
])

In [25]:
X_train_w2v_tensor = torch.FloatTensor(X_train_w2v)

X_test_w2v_tensor = torch.FloatTensor(X_test_w2v)

y_train_w2v_tensor = torch.FloatTensor(
    y_train.values
).reshape(-1, 1)

In [26]:
print("Training Word2Vec shape:", X_train_w2v_tensor.shape)
print("Testing Word2Vec shape:", X_test_w2v_tensor.shape)

Training Word2Vec shape: torch.Size([800, 200])
Testing Word2Vec shape: torch.Size([200, 200])

In [27]:
input_size = X_train_w2v_tensor.shape[1]

model_w2v = nn.Sequential(

    nn.Linear(input_size, 128),
    nn.ReLU(),

    nn.Linear(128, 64),
    nn.ReLU(),

    nn.Linear(64, 32),
    nn.ReLU(),

    nn.Linear(32, 1)
)

print(model_w2v)

Sequential(
  (0): Linear(in_features=200, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=32, bias=True)
  (5): ReLU()
  (6): Linear(in_features=32, out_features=1, bias=True)
)

In [28]:
loss_function = nn.BCEWithLogitsLoss()

optimizer = torch.optim.Adam(
    model_w2v.parameters(),
    lr=0.001
)

In [29]:
epochs = 15

for epoch in range(epochs):

    model_w2v.train()

    # Forward pass
    outputs = model_w2v(X_train_w2v_tensor)

    # Calculate loss
    loss = loss_function(
        outputs,
        y_train_w2v_tensor
    )

    # Backpropagation
    loss.backward()

    # Update weights
    optimizer.step()

    # Clear gradients
    optimizer.zero_grad()

    print(
        f"Epoch {epoch + 1}/{epochs} - Loss: {loss.item():.4f}"
    )

Epoch 1/15 - Loss: 0.6932
Epoch 2/15 - Loss: 0.6932
Epoch 3/15 - Loss: 0.6931
Epoch 4/15 - Loss: 0.6931
Epoch 5/15 - Loss: 0.6931
Epoch 6/15 - Loss: 0.6931
Epoch 7/15 - Loss: 0.6931
Epoch 8/15 - Loss: 0.6931
Epoch 9/15 - Loss: 0.6931
Epoch 10/15 - Loss: 0.6930
Epoch 11/15 - Loss: 0.6930
Epoch 12/15 - Loss: 0.6930
Epoch 13/15 - Loss: 0.6930
Epoch 14/15 - Loss: 0.6930
Epoch 15/15 - Loss: 0.6930

In [30]:
model_w2v.eval()

with torch.no_grad():

    test_outputs = model_w2v(
        X_test_w2v_tensor
    )

    test_probabilities = torch.sigmoid(
        test_outputs
    )

    predictions_w2v = (
        test_probabilities >= 0.5
    ).int().numpy().flatten()

accuracy_w2v = accuracy_score(
    y_test,
    predictions_w2v
)

print(f"Test Accuracy: {accuracy_w2v:.3f}")

Test Accuracy: 0.480